apiVersion: v1
kind: Secret
metadata:
  name: private-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/bluewhalekr/eimmo-infra
  username: not-used
  password: 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
