apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
data:
  service.slack: |
    token: $slack-token
  subscriptions: |
    - recipients:
        - slack:deploy
      triggers:
        - on-sync-succeeded
#  trigger.on-sync-succeeded: |
#    - description: Application is synced and healthy. Triggered once per commit.
#      oncePer: app.status.sync.revision
#      send:
#      - app-deployed
#      when: app.status.operationState.phase in ['Succeeded'] and app.status.health.status == 'Healthy'
#  template.app-deployed: |
#    message: |
#      {{if eq .serviceType "slack"}}:white_check_mark:{{end}} Application {{.app.metadata.name}} has been successfully synced at {{.app.status.operationState.finishedAt}}.
#    slack:
#      attachments: |
#        [{
#          "title": "{{ .app.metadata.name}}",
#          "title_link":"{{.context.argocdUrl}}/applications/{{.app.metadata.name}}",
#          "color": "#18be52",
#          "fields": [
#          {
#            "title": "Sync Status",
#            "value": "{{.app.status.sync.status}}",
#            "short": true
#          },
#          {
#            "title": "Repository",
#            "value": "{{.app.spec.source.repoURL}}",
#            "short": true
#          }
#          {{range $index, $c := .app.status.conditions}}
#          {{if not $index}},{{end}}
#          {{if $index}},{{end}}
#          {
#            "title": "{{$c.type}}",
#            "value": "{{$c.message}}",
#            "short": true
#          }
#          {{end}}
#          ]
#        }]
---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-notifications-secret
stringData:
  slack-token: $slack-token
