name: admin, indoor, app stg/perf 환경을 배포한다

on:
  workflow_dispatch:
    inputs:
      tag:
        description: '릴리즈 버전을 입력합니다. (릴리즈 브랜치 버전)'
        required: true
      version:
        description: '서비스 버전을 입력합니다. (가장 뒷자리 숫자)'
        required: true
      indoor_api:
        description: "indoor-api 배포"
        type: boolean
        required: true
        default: true
      admin_api:
        description: "admin-api 배포"
        type: boolean
        required: true
        default: true
      app_api:
        description: "app-api 배포"
        type: boolean
        required: true
        default: true

jobs:
  deploy_indoor_api:
    runs-on: ubuntu-latest
    if: ${{ inputs.indoor_api == true }}
    name: ${{ inputs.env }} 환경 ${{ inputs.tag }}.indoor-api-${{ inputs.version }} 배포한다
    steps:
    - run: echo ${{ inputs.env }} 환경 ${{ inputs.tag }}.indoor-api-${{ inputs.version }}

  deploy_admin_api:
    runs-on: ubuntu-latest
    if: ${{ inputs.admin_api == true }}
    name: ${{ inputs.env }} 환경 ${{ inputs.tag }}.admin-api-${{ inputs.version }} 배포한다
    steps:
    - run: echo ${{ inputs.env }} 환경 ${{ inputs.tag }}.admin-api-${{ inputs.version }}
    
  deploy_app_api:
    runs-on: ubuntu-latest
    if: ${{ inputs.app_api == true }}
    name: ${{ inputs.env }} 환경 ${{ inputs.tag }}.app-api-${{ inputs.version }} 배포한다
    steps:
    - run: echo ${{ inputs.env }} 환경 ${{ inputs.tag }}.app-api-${{ inputs.version }}
